builders:
  flutter_quick_db|build_db:
    import: "package:flutter_quick_db/flutter_quick_db.dart"
    builder_factories: [ "buildDb" ]
    build_extensions: { ".dart": [ ".g.dart" ] }
    auto_apply: root_package
    build_to: source
    applies_builders: [ ]